import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import fs from 'fs';

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const buildDir = "build";

// build 디렉토리 생성
if (!fs.existsSync(buildDir)) {
	fs.mkdirSync(buildDir, { recursive: true });
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: `${buildDir}/main.js`,
	minify: prod,
});

// CSS 파일 복사
if (fs.existsSync('src/styles.css')) {
	fs.copyFileSync('src/styles.css', `${buildDir}/styles.css`);
	console.log('✓ styles.css copied');
}

// manifest.json 복사
if (fs.existsSync('manifest.json')) {
	fs.copyFileSync('manifest.json', `${buildDir}/manifest.json`);
	console.log('✓ manifest.json copied');
}

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
